name: env_gnn
channels:
  - conda-forge
dependencies:
  - python=3.7
  - tensorflow=1.13.1
  - keras=2.2.4
  - keras-applications
  - keras-preprocessing
  - tensorboard=1.13.1
  - rdkit=2019.09.1
  - boost-cpp>=1.70,<1.74
  - boost>=1.70,<1.74
  - pip
  - pip:
      - absl-py==0.8.1
      - astor==0.8.0
      - grpcio==1.16.1
      - h5py==2.8.0
      - markdown==3.1.1
      - matplotlib==3.1.2
      - numpy==1.17.3
      - pandas==0.25.3
      - protobuf==3.19.6
      - scikit-learn==0.21.3
      - scipy==1.3.3
      - opencv-python==4.5.2.52
      - fastapi
      - uvicorn